server:
  port: 10001

spring:
  application:
    name: gateway-demo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: licy-demo
    gateway:
      routes: # 路由配置
        - id: cloud-demo
          uri: lb://cloud-demo
          predicates:
            - Path=/hello/**