server:
  port: 10010

spring:
  application:
    name: cloud-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: licy-test
    circuit breaker:
      hystrix:
        enabled: true