server:
  port: 10010

spring:
  application:
    name: cloud-demo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: licy-demo
    circuitbreaker:
      hystrix:
        enabled: true